// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFTvFQ4nYPrVB6yVL3vxLp9yA_xpRYO-8',
    appId: '1:679044916421:web:5d6b3e7355135d83a8bcac',
    messagingSenderId: '679044916421',
    projectId: 'overspeed-defense-system-56660',
    authDomain: 'overspeed-defense-system-56660.firebaseapp.com',
    storageBucket: 'overspeed-defense-system-56660.firebasestorage.app',
    measurementId: 'G-5GRQC17K4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAffWzfkwKZlkaUVUqAaTTPeWJtG2mJOPk',
    appId: '1:679044916421:android:21597c8c8264cabca8bcac',
    messagingSenderId: '679044916421',
    projectId: 'overspeed-defense-system-56660',
    storageBucket: 'overspeed-defense-system-56660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuoUDefg3UEwML-cSYj-Y2rU8u9NjjwyY',
    appId: '1:679044916421:ios:536e1dfbeabdbd60a8bcac',
    messagingSenderId: '679044916421',
    projectId: 'overspeed-defense-system-56660',
    storageBucket: 'overspeed-defense-system-56660.firebasestorage.app',
    iosBundleId: 'com.example.speedDefenseSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuoUDefg3UEwML-cSYj-Y2rU8u9NjjwyY',
    appId: '1:679044916421:ios:536e1dfbeabdbd60a8bcac',
    messagingSenderId: '679044916421',
    projectId: 'overspeed-defense-system-56660',
    storageBucket: 'overspeed-defense-system-56660.firebasestorage.app',
    iosBundleId: 'com.example.speedDefenseSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFTvFQ4nYPrVB6yVL3vxLp9yA_xpRYO-8',
    appId: '1:679044916421:web:e2042cd7fea7b00fa8bcac',
    messagingSenderId: '679044916421',
    projectId: 'overspeed-defense-system-56660',
    authDomain: 'overspeed-defense-system-56660.firebaseapp.com',
    storageBucket: 'overspeed-defense-system-56660.firebasestorage.app',
    measurementId: 'G-WHV3MCQ636',
  );
}
